const TABLE_TOP_LEFT = Vector2i(7, 13)
const TABLE_TOP_MIDDLE = Vector2i(8, 13)
const TABLE_TOP_RIGHT = Vector2i(9, 13)
const TABLE_BOTTOM_LEFT = Vector2i(7, 14)
const TABLE_BOTTOM_MIDDLE = Vector2i(8, 14)
const TABLE_BOTTOM_RIGHT = Vector2i(9, 14)

const W_COUCH_TOP_LEFT = Vector2i(4, 72)
const W_COUCH_TOP_MIDDLE = Vector2i(5, 72)
const W_COUCH_TOP_RIGHT = Vector2i(6, 72)
const W_COUCH_BOTTOM_LEFT = Vector2i(4, 73)
const W_COUCH_BOTTOM_MIDDLE = Vector2i(5, 73)
const W_COUCH_BOTTOM_RIGHT = Vector2i(6, 73)


const FURNITURE_TILES = [
	TABLE_TOP_LEFT,
	TABLE_TOP_MIDDLE,
	TABLE_TOP_RIGHT,
	TABLE_BOTTOM_LEFT,
	TABLE_BOTTOM_MIDDLE,
	TABLE_BOTTOM_RIGHT,
	
	W_COUCH_TOP_LEFT,
	W_COUCH_TOP_MIDDLE,
	W_COUCH_TOP_RIGHT,
	W_COUCH_BOTTOM_LEFT,
	W_COUCH_BOTTOM_MIDDLE,
	W_COUCH_BOTTOM_RIGHT
]
