const TABLE_TOP_LEFT = Vector2i(7, 13)
const TABLE_TOP_MIDDLE = Vector2i(8, 13)
const TABLE_TOP_RIGHT = Vector2i(9, 13)
const TABLE_BOTTOM_LEFT = Vector2i(7, 14)
const TABLE_BOTTOM_MIDDLE = Vector2i(8, 14)
const TABLE_BOTTOM_RIGHT = Vector2i(9, 14)

const W_COUCH_TOP_LEFT = Vector2i(4, 72)
const W_COUCH_TOP_MIDDLE = Vector2i(5, 72)
const W_COUCH_TOP_RIGHT = Vector2i(6, 72)
const W_COUCH_BOTTOM_LEFT = Vector2i(4, 73)
const W_COUCH_BOTTOM_MIDDLE = Vector2i(5, 73)
const W_COUCH_BOTTOM_RIGHT = Vector2i(6, 73)

const B_COUCH_TOP_LEFT = Vector2i(1, 72)
const B_COUCH_TOP_MIDDLE = Vector2i(2, 72)
const B_COUCH_TOP_RIGHT = Vector2i(3, 72)
const B_COUCH_BOTTOM_LEFT = Vector2i(1, 73)
const B_COUCH_BOTTOM_MIDDLE = Vector2i(2, 73)
const B_COUCH_BOTTOM_RIGHT = Vector2i(3, 73)

const BR_COUCH_TOP_LEFT = Vector2i(7, 72)
const BR_COUCH_TOP_MIDDLE = Vector2i(9, 72)
const BR_COUCH_TOP_RIGHT = Vector2i(8, 72)
const BR_COUCH_BOTTOM_LEFT = Vector2i(7, 73)
const BR_COUCH_BOTTOM_MIDDLE = Vector2i(9, 73)
const BR_COUCH_BOTTOM_RIGHT = Vector2i(8, 73)

const CARPET_1_TOP_LEFT = Vector2i(3, 42)
const CARPET_1_TOP_MIDDLE = Vector2i(4, 42)
const CARPET_1_TOP_RIGHT = Vector2i(5, 42)
const CARPET_1_BOTTOM_LEFT = Vector2i(3, 43)
const CARPET_1_BOTTOM_MIDDLE = Vector2i(4, 43)
const CARPET_1_BOTTOM_RIGHT = Vector2i(5, 43)

const CARPET_2_TOP_LEFT = Vector2i(0, 42)
const CARPET_2_TOP_MIDDLE = Vector2i(1, 42)
const CARPET_2_TOP_RIGHT = Vector2i(2, 42)
const CARPET_2_BOTTOM_LEFT = Vector2i(0, 43)
const CARPET_2_BOTTOM_MIDDLE = Vector2i(1, 43)
const CARPET_2_BOTTOM_RIGHT = Vector2i(2, 43)

const FIREPLACE_1_TOP_LEFT = Vector2i(4, 68)
const FIREPLACE_1_TOP_RIGHT = Vector2i(5, 68)
const FIREPLACE_1_MIDDLE_LEFT = Vector2i(4, 69)
const FIREPLACE_1_MIDDLE_RIGHT = Vector2i(5, 69)
const FIREPLACE_1_BOTTOM_LEFT = Vector2i(4, 70)
const FIREPLACE_1_BOTTOM_RIGHT = Vector2i(5, 70)

const FIREPLACE_2_TOP_LEFT = Vector2i(9, 86)
const FIREPLACE_2_TOP_RIGHT = Vector2i(10, 86)
const FIREPLACE_2_MIDDLE_LEFT = Vector2i(9, 87)
const FIREPLACE_2_MIDDLE_RIGHT = Vector2i(10, 87)
const FIREPLACE_2_BOTTOM_LEFT = Vector2i(9, 88)
const FIREPLACE_2_BOTTOM_RIGHT = Vector2i(10, 88)

const FIREPLACE_3_TOP_LEFT = Vector2i(14, 84)
const FIREPLACE_3_TOP_RIGHT = Vector2i(15, 84)
const FIREPLACE_3_MIDDLE_LEFT = Vector2i(14, 85)
const FIREPLACE_3_MIDDLE_RIGHT = Vector2i(15, 85)
const FIREPLACE_3_BOTTOM_LEFT = Vector2i(14, 86)
const FIREPLACE_3_BOTTOM_RIGHT = Vector2i(15, 86)

const BOOKSHELF_1_TOP_LEFT = Vector2i(10, 68)
const BOOKSHELF_1_TOP_RIGHT = Vector2i(11, 68)
const BOOKSHELF_1_MIDDLE_LEFT = Vector2i(10, 69)
const BOOKSHELF_1_MIDDLE_RIGHT = Vector2i(11, 69)
const BOOKSHELF_1_BOTTOM_LEFT = Vector2i(10, 70)
const BOOKSHELF_1_BOTTOM_RIGHT = Vector2i(11, 70)

const BOOKSHELF_2_TOP_LEFT = Vector2i(12, 68)
const BOOKSHELF_2_TOP_RIGHT = Vector2i(13, 68)
const BOOKSHELF_2_MIDDLE_LEFT = Vector2i(12, 69)
const BOOKSHELF_2_MIDDLE_RIGHT = Vector2i(13, 69)
const BOOKSHELF_2_BOTTOM_LEFT = Vector2i(12, 70)
const BOOKSHELF_2_BOTTOM_RIGHT = Vector2i(13, 70)

const BOOKSHELF_3_TOP_LEFT = Vector2i(12, 71)
const BOOKSHELF_3_TOP_RIGHT = Vector2i(13, 71)
const BOOKSHELF_3_MIDDLE_LEFT = Vector2i(12, 72)
const BOOKSHELF_3_MIDDLE_RIGHT = Vector2i(13, 72)
const BOOKSHELF_3_BOTTOM_LEFT = Vector2i(12, 73)
const BOOKSHELF_3_BOTTOM_RIGHT = Vector2i(13, 73)

const ART_1_TOP = Vector2i(0, 70)
const ART_1_BOTTOM = Vector2i(0, 71)
const ART_2_TOP = Vector2i(1, 70)
const ART_2_BOTTOM = Vector2i(1, 71)
const ART_3_TOP = Vector2i(2, 70)
const ART_3_BOTTOM = Vector2i(2, 71)
const ART_4_TOP = Vector2i(0, 72)
const ART_4_BOTTOM = Vector2i(0, 73)
const ART_5_TOP = Vector2i(0, 74)
const ART_5_BOTTOM = Vector2i(0, 75)
const ART_6_TOP = Vector2i(0, 76)
const ART_6_BOTTOM = Vector2i(0, 77)

const MIRROR_1_TOP = Vector2i(3, 66)
const MIRROR_1_BOTTOM = Vector2i(3, 67)
const MIRROR_2_TOP = Vector2i(3, 68)
const MIRROR_2_BOTTOM = Vector2i(3, 69)
const MIRROR_3_TOP = Vector2i(3, 70)
const MIRROR_3_BOTTOM = Vector2i(3, 71)

const LAMP_UP = Vector2i(15, 57)
const LAMP_DOWN = Vector2i(15, 58)

const FURNITURE_TILES = [
	TABLE_TOP_LEFT,
	TABLE_TOP_MIDDLE,
	TABLE_TOP_RIGHT,
	TABLE_BOTTOM_LEFT,
	TABLE_BOTTOM_MIDDLE,
	TABLE_BOTTOM_RIGHT,
	
	B_COUCH_TOP_LEFT,
	B_COUCH_TOP_MIDDLE,
	B_COUCH_TOP_RIGHT,
	B_COUCH_BOTTOM_LEFT,
	B_COUCH_BOTTOM_MIDDLE,
	B_COUCH_BOTTOM_RIGHT,

	BR_COUCH_TOP_LEFT,
	BR_COUCH_TOP_MIDDLE,
	BR_COUCH_TOP_RIGHT,
	BR_COUCH_BOTTOM_LEFT,
	BR_COUCH_BOTTOM_MIDDLE,
	BR_COUCH_BOTTOM_RIGHT,

	W_COUCH_TOP_LEFT,
	W_COUCH_TOP_MIDDLE,
	W_COUCH_TOP_RIGHT,
	W_COUCH_BOTTOM_LEFT,
	W_COUCH_BOTTOM_MIDDLE,
	W_COUCH_BOTTOM_RIGHT
]

static func get_couches():
	var BLUE_COUCH = RectObject.new(
		B_COUCH_TOP_LEFT,
		B_COUCH_TOP_MIDDLE,
		B_COUCH_TOP_RIGHT,
		B_COUCH_BOTTOM_LEFT,
		B_COUCH_BOTTOM_MIDDLE,
		B_COUCH_BOTTOM_RIGHT
	)

	var BROWN_COUCH = RectObject.new(
		BR_COUCH_TOP_LEFT,
		BR_COUCH_TOP_MIDDLE,
		BR_COUCH_TOP_RIGHT,
		BR_COUCH_BOTTOM_LEFT,
		BR_COUCH_BOTTOM_MIDDLE,
		BR_COUCH_BOTTOM_RIGHT
	)

	var WHITE_COUCH = RectObject.new(
		W_COUCH_TOP_LEFT,
		W_COUCH_TOP_MIDDLE,
		W_COUCH_TOP_RIGHT,
		W_COUCH_BOTTOM_LEFT,
		W_COUCH_BOTTOM_MIDDLE,
		W_COUCH_BOTTOM_RIGHT
	)
	return [BLUE_COUCH, WHITE_COUCH, BROWN_COUCH]
	
static func get_carpets():
	var CARPET_1 = RectObject.new(
		CARPET_1_TOP_LEFT,
		CARPET_1_TOP_MIDDLE,
		CARPET_1_TOP_RIGHT,
		CARPET_1_BOTTOM_LEFT,
		CARPET_1_BOTTOM_MIDDLE,
		CARPET_1_BOTTOM_RIGHT,	
	)

	var CARPET_2 = RectObject.new(
		CARPET_2_TOP_LEFT,
		CARPET_2_TOP_MIDDLE,
		CARPET_2_TOP_RIGHT,
		CARPET_2_BOTTOM_LEFT,
		CARPET_2_BOTTOM_MIDDLE,
		CARPET_2_BOTTOM_RIGHT,	
	)

	return [CARPET_1, CARPET_2]

static func get_wall_deco():
	var FIREPLACE_1 = WallDeco.new(
		FIREPLACE_1_TOP_LEFT,
		null,
		FIREPLACE_1_TOP_RIGHT,
		FIREPLACE_1_MIDDLE_LEFT,
		null,
		FIREPLACE_1_MIDDLE_RIGHT,
		FIREPLACE_1_BOTTOM_LEFT,
		null,
		FIREPLACE_1_BOTTOM_RIGHT,
	)

	var FIREPLACE_2 = WallDeco.new(
		FIREPLACE_2_TOP_LEFT,
		null,
		FIREPLACE_2_TOP_RIGHT,
		FIREPLACE_2_MIDDLE_LEFT,
		null,
		FIREPLACE_2_MIDDLE_RIGHT,
		FIREPLACE_2_BOTTOM_LEFT,
		null,
		FIREPLACE_2_BOTTOM_RIGHT,
	)

	var FIREPLACE_3 = WallDeco.new(
		FIREPLACE_3_TOP_LEFT,
		null,
		FIREPLACE_3_TOP_RIGHT,
		FIREPLACE_3_MIDDLE_LEFT,
		null,
		FIREPLACE_3_MIDDLE_RIGHT,
		FIREPLACE_3_BOTTOM_LEFT,
		null,
		FIREPLACE_3_BOTTOM_RIGHT,
	)

	var BOOKSHELF_1 = WallDeco.new(
		BOOKSHELF_1_TOP_LEFT,
		null,
		BOOKSHELF_1_TOP_RIGHT,
		BOOKSHELF_1_MIDDLE_LEFT,
		null,
		BOOKSHELF_1_MIDDLE_RIGHT,
		BOOKSHELF_1_BOTTOM_LEFT,
		null,
		FIREPLACE_1_BOTTOM_RIGHT,
	)

	var BOOKSHELF_2 = WallDeco.new(
		BOOKSHELF_2_TOP_LEFT,
		null,
		BOOKSHELF_2_TOP_RIGHT,
		BOOKSHELF_2_MIDDLE_LEFT,
		null,
		BOOKSHELF_2_MIDDLE_RIGHT,
		BOOKSHELF_2_BOTTOM_LEFT,
		null,
		BOOKSHELF_2_BOTTOM_RIGHT,
	)

	var BOOKSHELF_3 = WallDeco.new(
		BOOKSHELF_3_TOP_LEFT,
		null,
		BOOKSHELF_3_TOP_RIGHT,
		BOOKSHELF_3_MIDDLE_LEFT,
		null,
		BOOKSHELF_3_MIDDLE_RIGHT,
		BOOKSHELF_3_BOTTOM_LEFT,
		null,
		BOOKSHELF_3_BOTTOM_RIGHT,
	)

	return [FIREPLACE_1, FIREPLACE_2, FIREPLACE_3, BOOKSHELF_1, BOOKSHELF_2, BOOKSHELF_3]

static func get_wall_art():
	var ART_1 = WallDeco.new(
		null,
		ART_1_TOP,
		null,
		null,
		ART_1_BOTTOM,
	)

	var ART_2 = WallDeco.new(
		null,
		ART_2_TOP,
		null,
		null,
		ART_2_BOTTOM,
	)

	var ART_3 = WallDeco.new(
		null,
		ART_3_TOP,
		null,
		null,
		ART_3_BOTTOM,
	)

	var ART_4 = WallDeco.new(
		null,
		ART_4_TOP,
		null,
		null,
		ART_4_BOTTOM,
	)

	var ART_5 = WallDeco.new(
		null,
		ART_5_TOP,
		null,
		null,
		ART_5_BOTTOM,
	)

	var ART_6 = WallDeco.new(
		null,
		ART_6_TOP,
		null,
		null,
		ART_6_BOTTOM,
	)

	var MIRROR_1 = WallDeco.new(
		null,
		MIRROR_1_TOP,
		null,
		null,
		MIRROR_1_BOTTOM,
	)

	var MIRROR_2 = WallDeco.new(
		null,
		MIRROR_2_TOP,
		null,
		null,
		MIRROR_2_BOTTOM,
	)

	var MIRROR_3 = WallDeco.new(
		null,
		MIRROR_3_TOP,
		null,
		null,
		MIRROR_3_BOTTOM,
	)
	
	return [ART_1, ART_2, ART_3, ART_4, ART_5, ART_6, MIRROR_1, MIRROR_2, MIRROR_3]

